import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    companies: [
      "Apple",
      "AMD",
      "Bed Bath&Beyond",
      "Endo Int",
      "Intel",
      "Qualcomm",
      "FuelCell Energy",
      "Qurate Retail A",
      "Microsoft",
      "Tesla",
      "United Airlines Holdings",
      "Sirius XM",
      "Plug Power",
      "Assertio Therapeutics",
      "Comcast",
      "Cisco",
      "Cassava Sciences",
      "JetBlue",
      "Activision Blizzard",
      "Viatris",
      "Micron",
      "APA Corp",
      "Novavax",
      "ViacomCBS",
      "Expedia",
      "Goodyear Tire & Rubber Co",
      "Dynavax",
      "Starbucks",
      "Remark",
      "CSX",
      "Riot Blockchain",
      "Walgreens Boots",
      "Kraft Heinz",
      "Host Hotels Resorts",
      "Color Star Technology Co",
      "Huntington Bancshares",
      "NortonLifeLock Inc",
      "Applied Materials",
      "Himax",
      "ON Semiconductor",
      "Gilead",
      "Marvell",
      "Trip.com ADR",
      "Discovery A",
      "Clean Energy",
      "Microchip",
      "Vaxart",
      "ACI Worldwide",
      "News Corp A",
      "Nektar",
      "Fiserv",
      "Wynn Resorts",
      "Netflix",
      "Gevo",
      "AGNC Invest",
      "Microvision",
      "Big 5",
      "Cinedigm",
      "Amazon.com",
      "Luokung Tech",
      "BioCryst",
      "eBay",
      "Exelon",
      "Dollar Tree",
      "Keurig Dr Pepper",
      "Texas Instruments",
      "Xcel Energy",
      "Monster Beverage",
      "Baidu",
      "DISH Network",
      "Flex",
      "Viavi Solutions",
      "PepsiCo",
      "Amicus",
      "Cognex",
      "Analog Devices",
      "Agenus",
      "Curis",
      "Ballard",
      "Nuance Communications",
      "Citrix Systems",
      "Liberty Global",
      "Marriott Int",
      "SunPower",
      "BGC Partners",
      "Clovis",
      "NXP",
      "Sharplink Gaming",
      "Dentsply",
      "Western Digital",
      "EXACT Sciences",
      "Amyris",
      "VBI Vaccines",
      "Electronic Arts",
      "Limelight",
      "First Solar",
      "Infinera",
      "Fifth Third",
      "Ferroglobe",
      "Cerner",
      "Adobe",
      "Aeterna Zentaris",
      "New York Mortgage",
      "Codexis",
      "Horizon Pharma",
      "Discovery Communications C",
      "Incyte",
      "Fastenal",
      "Hologic",
      "Honeywell",
      "Amgen",
      "Geron",
      "Vertex",
      "Cerus",
      "The Cheesecake",
      "Patterson-UTI Energy",
      "Accuray",
      "Xerox",
      "Cross Country",
      "Pacific Biosciences",
      "Mattel",
      "Akamai",
      "Lam Research",
      "Costco",
      "Rigel",
      "MannKind",
      "Rent-A-Center",
      "ImmunoGen",
      "Retail Opportunity",
      "Xilinx",
      "Liberty Global C",
      "Newell Brands",
      "BIOLASE",
      "American Electric Power",
      "Alphabet A",
      "Seelos Therapeutics",
      "Broadcom",
      "Ironwood",
      "Cognizant A",
      "Green Plains Energy",
      "Healthcare Services",
      "SLM",
      "Take-Two",
      "Aehr Test Systems",
      "Kopin",
      "Inseego",
      "Teradyne",
      "Fortinet",
      "KLA-Tencor",
      "Allscripts",
      "Gentex",
      "SSR Mining",
      "Pan American Silver",
      "Seagate",
      "Alto Ingredients",
      "Cytokinetics Inc",
      "Steel Dynamics",
      "Intuitive Surgical",
      "Illumina",
      "PACCAR",
      "Kratos Defense&Security",
      "Hawaiian",
      "BioDelivery Sciences",
      "CoStar",
      "Cyren",
      "Ross Stores",
      "Yandex",
      "Yellow",
      "Biomarin Pharma",
      "Euronet",
      "Expeditors Washington",
      "Intuit",
      "Denny’s",
      "ADP",
      "Bimi International Medical",
      "CME Group",
      "Alphatecs",
      "Investors Bancorp",
      "NetEase",
      "Autodesk",
      "Infinity",
      "NuVasive",
      "NetApp",
      "Alimera",
      "Alkermes Plc",
      "Sarepta",
      "Stagwell",
      "OraSure",
      "CTi Biopharma",
      "Celsion",
      "Paychex",
      "Hollysys Automation Tech",
      "Perficient",
      "Quidel",
      "Urban Outfitters",
      "Polarityte",
      "eHealth",
      "GTX Inc",
      "Lattice",
      "Zions",
      "II-VI",
      "PTC",
      "Bridgeline Digital",
      "Neurocrine",
      "Immersion Corp",
      "ACADIA",
      "PacWest",
      "Entegris",
      "Durect",
      "Avadel Pharma",
      "Kulicke&Soffa",
      "Omeros",
      "Golar",
      "Athersys",
      "CBAK Energy",
      "CH Robinson",
      "ENGlobal",
      "MercadoLibre",
      "Ionis Pharma",
      "Crocs",
      "Overstockcom",
      "NetScout",
      "Amkor",
      "Garmin",
      "MKS Instruments",
      "Halozyme",
      "LivePerson",
      "Harmonic",
      "QuinStreet",
      "Papa John's",
      "National Instruments",
      "Alpha & Omega Semiconductor",
      "Canadian Solar Inc",
      "Avid Bioservices",
      "T Rowe",
      "Fuel Tech",
      "Urban One Inc",
      "Huazhu",
      "Cadence Design",
      "Extreme",
      "ArcBest Corp",
      "Biogen",
      "Mitek",
      "Coca-Cola European",
      "Atlas Air",
      "Repligen",
      "Career",
      "Catalyst Pharmaceuticals",
      "Charter Communications",
      "Henry Schein",
      "Carparts.Com",
      "Seagen",
      "Principal Financial",
      "Check Point Software",
      "Universal Display",
      "Lexicon",
      "Booking",
      "Option Care Health",
      "Insulet",
      "Charles&Colvard",
      "Kandi",
      "Home BancShares",
      "The Hain Celestial",
      "Fulton",
      "Northern Trust",
      "Alnylam",
      "Corcept",
      "Neptune Wellness Solutions",
      "Arrowhead Pharma",
      "MillerKnoll",
      "News Corp",
      "Iridium",
      "Hasbro",
      "Rave Restaurant",
      "Shyft Group Inc",
      "Red Robin Gourmet Burgers",
      "National CineMedia",
      "Dawson Geophysical",
      "Fluidigm",
      "Royal Gold",
      "IAC/InterActiveCorp",
      "AcelRx",
      "Myriad Genetics",
      "Information Services",
      "LHC Group",
      "Grifols ADR",
      "RealNetworks",
      "Cirrus",
      "Compugen Ltd",
      "MicroStrategy",
      "US Well Services",
      "BSQUARE",
      "Rambus",
      "JB Hunt",
      "Interactive Brokers",
      "MakeMyTrip",
      "Arena Pharma",
      "Perion Network",
      "Hope Bancorp",
      "East West Bancorp",
      "Nasdaq Inc",
      "Recon Technology",
      "CVB Financial",
      "Jack Henry&Associates",
      "Capitol Federal",
      "VeriSign",
      "Sotherly Hotels",
      "Equinix",
      "Open Text",
      "ANSYS",
      "Pacira",
      "Idera Pharma",
      "Patterson",
      "Echo Global",
      "Rockwell Medical",
      "ICON PLC",
      "Cohu",
      "Female Health",
      "Insmed",
      "Protagenic Therapeutics",
      "Amedisys",
      "Eagle Bulk Shipping",
      "Freightcar",
      "Brooks Automation",
      "Axcelis",
      "Calumet",
      "Jazz Pharma",
      "Northwest Bancshares",
      "Primoris",
      "Acadia Healthcare",
      "Ceragon",
      "Simply Good Foods",
      "Landstar",
      "Energy Recovery",
      "Coherus BioSciences",
      "AtriCure",
      "DexCom",
      "Columbia Banking",
      "Cincinnati Financial",
      "Cracker Barrel Old",
      "The Ensign",
      "Methanex",
      "BJs Restaurants",
      "Lamar",
      "Ribbon Com",
      "First Midwest",
      "Consolidated Communications",
      "China Jo-Jo Drugstores",
      "Saia",
      "Autoweb",
      "Green Brick Partners Inc",
      "iRobot",
      "Beacon Roofing",
      "FormFactor",
      "Blackbaud",
      "Kimball",
      "Digital Ally",
      "Bank Ozk",
      "Clearfield",
      "Encore Capital",
      "Hancock Whitney",
      "Align",
      "Glacier",
      "Covenant",
      "Hudson",
      "OceanFirst",
      "Ruth's Hospitality",
      "Ziff Davis",
      "Mercury",
      "ADTRAN",
      "MoSys",
      "Monolithic",
      "Farmer Bros. Co",
      "Acacia Research",
      "Kearny Financial",
      "Avid",
      "Mercer Int",
      "The Chefs Warehouse",
      "F5 Networks",
      "Century Casinos",
      "G-III Apparel",
      "RadNet",
      "Nexstar",
      "Heritage Financial Co",
      "Axon Enterprise",
      "LPL Financial",
      "First Interstate BancSystem",
      "Pixelworks",
      "Astrotech",
      "Newegg Commerce",
      "Diodes",
      "IDEXX Labs",
      "Radware",
      "Fortress Biotech",
      "ABIOMED",
      "Hibbett Sports",
      "Liquid Media",
      "First Financial Bankshares",
      "Nova Measuring Instruments Ltd",
      "Alterity Therapeutics",
      "Integra",
      "LightPath",
      "Alliance Resource",
      "Tivity Health",
      "Masimo",
      "Republic First Bancorp",
      "Stericycle",
      "Gilat Satellite Networks Ltd",
      "Jack In The Box",
      "First Merchants",
      "First Financial Bancorp",
      "Middleby Corp",
      "Icahn Enterprises",
      "Lantronix",
      "Eyepoint Pharma",
      "Heartland Express",
      "Globus Maritime",
      "Cathay",
      "Broadwind",
      "Celldex Therapeutics",
      "O’Reilly Automotive",
      "Merit",
      "AXT",
      "Ryanair ADR",
      "Meta Financial",
      "AngioDynamics",
      "Children’s Place",
      "Identiv",
      "Vericel Corp Ord",
      "Ameris",
      "Premier Financial",
      "Capital Product",
      "PotlatchDeltic",
      "NETGEAR",
      "Destination XL Group",
      "IPG Photonics",
      "Power Integrations",
      "MarketAxesss",
      "ODP",
      "Cintas",
      "Heritage Commerce",
      "PetMed Express",
      "Urban One D",
      "Neogen",
      "PRA Group Inc",
      "Meridian Interstate",
      "Progress",
      "ClearOne",
      "Insight Enterprises",
      "Itron",
      "BioLineRx",
      "Hub Group",
      "Conns",
      "1-800 FLOWERS.COM",
      "H&E Equipment",
      "Bottomline",
      "FirstCash",
      "Matrix",
      "Liberty Media Formula A",
      "SemiLEDS",
      "Insignia",
      "EW Scripps A",
      "Brookline Bancorp",
      "Commercial Vehicle",
      "Pegasystems",
      "Golden Entertainment",
      "Pacific Premier",
      "Magellan Health",
      "Research Frontiers",
      "Photronics",
      "NN Inc",
      "Sify",
      "Oncolytics Biotec",
      "Casella",
      "Commerce Bancshares",
      "Omnicell",
      "Churchill Downs",
      "51job",
      "Renasant",
      "First Busey",
      "CSG Systems",
      "NeuroMetrix",
      "Cowen Group",
      "Astec",
      "The Andersons",
      "Cytori Therapeutics",
      "Marten Transport",
      "Interface",
      "ID Systems",
      "The9 ADR",
      "Cardiovascular",
      "Manhattan Associates",
      "National Beverage",
      "Rush A",
      "Kirklands",
      "ARCA Biopharma",
      "Allegiant",
      "Pingtan Marine",
      "Luna",
      "Qumu Corp",
      "Koss",
      "Natures Sunshine",
      "ZW Data Action Technologies",
      "Sohu.Com",
      "Cal-Maine",
      "Pinnacle",
      "China HGS RE",
      "Harvard Bioscience",
      "Biocept",
      "Grand Canyon Education",
      "Ebix",
      "Cogent",
      "Heska",
      "O2Micro",
      "aTyr Pharma",
      "Clarus",
      "Enterprise Financial",
      "EMCORE",
      "Independent Bank",
      "Patrick",
      "American Superconductor",
      "Euroseas",
      "Communications Systems",
      "Fanhua",
      "Resources Connection",
      "Newtek",
      "Great Lakes Dredge&Dock",
      "Altra",
      "Ligand",
      "ExlServices",
      "Forward Air",
      "First Bancorp",
      "AVEO",
      "Helen of Troy Ltd",
      "Pool",
      "MGP Ingredients",
      "Aviat",
      "Addus",
      "Columbia Sportswear",
      "Kelly Services A",
      "Natus",
      "Novanta",
      "AAON",
      "Gibraltar Industries",
      "The Providence Service",
      "Monro Muffler Brake",
      "Caseys",
      "US Ecology",
      "International Bancshares",
      "Antelope Enterprise Holdings",
      "Rada Electronic Industries",
      "Exponent",
      "Gentherm",
      "Liquidity Services",
      "Nice ADR",
      "Albireo Pharma",
      "Columbus McKinnon",
      "Advanced Energy",
      "CMC Materials",
      "Kaiser",
      "Farmers National",
      "Statera Biopharma",
      "Citi Trends",
      "Lakeland Bancorp",
      "Lightbridge",
      "BOK Financial",
      "EZCORP",
      "Horizon Bancorp",
      "Central Garden&Pet A",
      "Gladstone Commercial",
      "Huron",
      "ManTech",
      "Capital Southwest",
      "America First Tax",
      "Maiden Holdings",
      "Creative Realities",
      "China Recycling Energy",
      "Raven",
      "Nordson",
      "Sellas Life Sciences",
      "icad",
      "Cutera",
      "Digi",
      "ADES",
      "Greenlight Capital Re",
      "Aeroportuario del Centro Norte",
      "Cresud SACIF",
      "Calavo Growers",
      "Loop Industries",
      "Inotiv",
      "InterDigital",
      "Otter Tail",
      "MediciNova",
      "Thermogenesis Holdings",
      "Rocky Brands",
      "Cyclacel",
      "Weatherford",
      "GSI Technology",
      "Heidrick&Struggles",
      "Hanmi",
      "Credit Acceptance",
      "Kforce",
      "PDF Solutions",
      "Flushing",
      "Lakeland Financial",
      "Comtech",
      "RBC Bearings",
      "Franklin Electric",
      "Allied Healthcare",
      "Camtek Ltd",
      "Dorman",
      "EDAP",
      "MYR Group",
      "AeroVironment",
      "Astronics",
      "Digimarc",
      "DSP Group",
      "Cadiz",
      "Loral Space",
      "CTI Industries",
      "Inter Parfums",
      "Genasys Inc",
      "CEVA",
      "Atlanticuss",
      "Middlesex Water",
      "Hudson Global Inc",
      "CalAmp",
      "Blueknight",
      "IRIDEX",
      "Innodata",
      "LSI Industries",
      "QuickLogic",
      "Erie Indemnity",
      "NBT Bancorp",
      "Acorda",
      "Plexus",
      "China Natural Resources",
      "American Software",
      "American Woodmark",
      "Engine Media Holdings Inc",
      "Pluristem",
      "Northfield Bancorp",
      "Amtech",
      "MGE Energy",
      "RCM Technologies",
      "NAPCO",
      "Landec",
      "Allot Communications",
      "Banner",
      "RCI Hospitality",
      "Allied Motion",
      "Heartland Financial",
      "Balchem",
      "Lancaster Colony",
      "ICU Medical",
      "Dime Community",
      "JAKKS Pacific",
      "Ingles",
      "Apogee",
      "PC-Tel",
      "Daktronics",
      "eGain",
      "NetSol",
      "Computer Programs&Systems",
      "Sanderson Farms",
      "Heritage-Crystal Clean",
      "Forrester",
      "Matthews",
      "PriceSmart",
      "Eagle",
      "OSI Systems",
      "Dmc Global",
      "Powell Industries",
      "Star Equity Holdings",
      "Sonoma Pharma",
      "Descartes Systems",
      "American Public Education",
      "CRA",
      "Macatawa Bank",
      "Old Second Bancorp",
      "McGrath",
      "AMERISAFE",
      "Independent Bank Corp",
      "Hallador",
      "DXP Enterprises",
      "QCR",
      "Nymox Pharmaceutical",
      "ICF International",
      "Horizon Finance",
      "Innospec",
      "The Hackett",
      "Achieve Life Sciences",
      "FARO",
      "Capstone Green Energy",
      "Bryn Mawr Bank",
      "Agilysys",
      "Delcath Systems",
      "Acer Therapeutics",
      "The First Bancshares",
      "Orthofix",
      "Colliers International",
      "Evolving Systems",
      "HealthStream",
      "Riverview",
      "First of Long Island",
      "Bank of Marin",
      "CECO Environmental",
      "Coherent",
      "Gaia Inc",
      "Anika",
      "Bel Fuse B",
      "BancFirst",
      "PC Connection",
      "Forward Industries",
      "Steel Connect",
      "China Finance",
      "Preferred Bank",
      "Littelfuse",
      "PFSweb",
      "AudioCodes",
      "BOS",
      "Richardson Electronics",
      "Monarch",
      "Hallmark",
      "Qurate Retail B",
      "Manhattan Bridge",
      "Highpeak Energy Acquisition",
      "US Global",
      "Peapack-Gladstone",
      "German American Bancorp",
      "Morningstar",
      "Taoping",
      "Cass",
      "Hooker Furniture",
      "Reading Int",
      "Americas Car-Mart",
      "Pure Cycle",
      "American National Insurance",
      "Dorchester Minerals",
      "City Holding",
      "IRSA Propiedades ADR",
      "Alpine Immune Sciences",
      "Lincoln Educational",
      "Genetic Technologies",
      "Central Garden&Pet",
      "Highways",
      "Haynes",
      "Stabilis Solutions",
      "Broadway Financial",
      "Cavco",
      "CNB Financial",
      "Donegal A",
      "INTL FCStone",
      "Lakeland Industries",
      "J & J Snack Foods",
      "ePlus",
      "Motorcar Parts",
      "Civista Bancshares",
      "Northwest Pipe",
      "First Community Bancshares",
      "Beasley",
      "MidWestOne",
      "Barrett",
      "Limoneira",
      "Bassett",
      "Safety Insurance",
      "Marchex",
      "Mind Technology",
      "PAM",
      "Innovative Solutions",
      "Intevac",
      "Lifetime Brands",
      "Key Tronic",
      "Hawkins",
      "Northeast Community",
      "Arrow",
      "Community Trust",
      "STRATA Skin Sciences",
      "Consolidated Water",
      "Sierra Bancorp",
      "Camden",
      "Marine Petroleum",
      "Good Times",
      "Euro Tech",
      "CorVel",
      "Mercantile",
      "Senstar Technologies",
      "Martin Midstream",
      "Janone",
      "Consumer Portfolio Services",
      "Flexsteel",
      "Mid Penn",
      "CF Bankshares",
      "Cumberland",
      "Citizens&Northern",
      "ATN Int",
      "ProPhase Labs",
      "Dynatronics",
      "Enstar",
      "KVH Industries",
      "Financial Institutions",
      "John B Sanfilippo&Son",
      "Ituran",
      "Vidler Water Resources",
      "UTStarcom",
      "BankFinancial",
      "First Citizens BancShares",
      "Data I/O",
      "China Automotive",
      "IES Holdings",
      "Aware",
      "Capital City Bank",
      "The Dixie",
      "Psychemedics",
      "ChipMOS Tech",
      "Carver",
      "CyberOptics",
      "StealthGas",
      "Coffee Holding",
      "Asure",
      "BCB Bancorp",
      "First Bancorp Inc",
      "Great Southern Bancorp",
      "Tenax Therapeutics",
      "Home Bancorp",
      "Gulf Island Fabrication",
      "ADDvantage",
      "Gulf Resources",
      "American National Bankshares",
      "Optical Cable",
      "Republic Bancorp",
      "Escalade",
      "Magic Sftware",
      "Orrstown",
      "US Gold",
      "AmeriServ",
      "Park Ohio Holdings",
      "Giga Media Ltd",
      "Great Elm Group",
      "Artesian",
      "Eastern Co",
      "Johnson Outdoors",
      "Performance Shipping",
      "Mesa Labs",
      "Reading Int B",
      "Indus Realty Trust",
      "Alico",
      "ATA",
      "P&F Industries",
      "Lifeway",
      "AstroNova",
      "CSI Compressco",
      "CVD Equipment",
      "Rush B",
      "Nortech",
      "Lumos Pharma Inc",
      "Educational Development",
      "Kingstone",
      "Marlin Business",
      "Ikonics",
      "Enterprise",
      "Coca-Cola Bottling",
      "Autoscope Technologies",
      "Perma-Fix Inc",
      "Airnet Tech",
      "Radcom",
      "Rocky Mountain Chocolate",
      "Points International",
      "Gencor",
      "Asia Pacific Wire & Cable",
      "The Intergroup",
      "Computer Task",
      "Electro-Sensors",
      "NVE Corporation",
      "Magyar",
      "Northrim",
      "Frp Holdings Ord",
      "National Bankshares",
      "Parke",
      "Diamond Hill",
      "Kazia Therapeutics ADR",
      "RGC Resources",
      "IntriCon",
      "OptimumBank Holdings",
      "Air T",
      "Burcon Nutrascience Corp",
      "Manitex",
      "LB Foster",
      "LCNB",
      "Codorus Valley",
      "MIND CTI",
      "1st Constitution Bancorp",
      "Hurco",
      "First Savings",
      "Gravity Co",
      "Norwood",
      "Natural Alternatives",
      "First Financial Northwest",
      "Arts-Way",
      "Oak Valley Bancorp",
      "Odyssey",
      "Community West Bancshares",
      "Geospace",
      "First United",
      "Preformed Line",
      "Pro-Dex",
      "Citizens Community",
      "BBQ Holdings",
      "Atlantic American",
      "Ohio Valley Banc",
      "Fonar",
      "Live Ventures",
      "Global Indemnity",
      "Eltek",
      "Northeast Bancorp",
      "Crown Crafts",
      "Ark Restaurants",
      "National Western Life Insurance",
      "Lawson",
      "RF Industries",
      "Century Bancorp",
      "Isleworth Healthcare Acquisition",
      "Pathfinder Bancorp",
      "Nathans Famous",
      "Provident",
      "Hawthorn Bancshares",
      "First Community",
      "Perma-Pipe Int",
      "Ames",
      "Cyanotech",
      "Fuwei Films Holdings",
      "Peoples North Carolina",
      "Malvern",
      "ImmuCell",
      "CSP",
      "Eagle Montana",
      "Omega Flex",
      "First Capital",
      "Ocean Bio-Chem",
      "Hingham Institution",
      "Central Valley Community",
      "Formula Systems ADR",
      "Investors Title",
      "Alithya A",
      "Home Federal Louisiana",
      "ATRION",
      "IF Bancorp",
      "First Business",
      "Frequency Electronics",
      "Mannatech",
      "Comstock",
      "ESSA Bancorp",
      "Greene County",
      "Guaranty Federal",
      "Northern Technologies",
      "ACNB",
      "Bonso Electronics Int",
      "Elmira Savings Bank",
      "Penns Woods",
      "C&F Financial",
      "Deswell Industries",
      "Kentucky First Federal",
      "Franklin Fin.",
      "Prudential Pennsylvania",
      "Old Point",
      "Kelly Services B",
      "Porter Bancorp",
      "Daily Journal Corp",
      "Discovery B",
      "Partner ADR",
      "Glen Burnie",
      "Auburn",
      "Bridgford",
      "Rubicon Tech",
      "Donegal B",
      "Citizens",
      "PrimeEnergy",
      "Jewett-Cameron Trading",
      "Lake Shore Bancorp",
      "Bel Fuse A",
      "Kewaunee",
      "Landmark",
      "J W Mays",
      "SB Financial",
      "Plumas",
      "Nicholas Financial",
      "Gyrodyne of America",
      "Liberty Global B",
      "Canterbury Park",
      "National Security",
      "Patriot National Bancorp",
      "Bank of South Carolina",
      "Colony Bankcorp",
      "Emclaire",
      "HMN Financial",
      "Optibase",
      "Oconee",
      "QAD A",
      "QAD B",
    ],
  },
});
